### ISSUE TITLE
Task list for Taxon

### ISSUE THREAD

**Issue by andrechalom** [opendatabio/opendatabio#50]
- [x] Specialist table
- [x] External API keys and links
- [x] Assemble / disassemble names
- [x] Integrate with remaining APIs. [Edit: done for IPNI, WIP Mycobank]
- [x] Autofill parent [Edit: working for genus and species, need to work with infra subsp forms. Will need more work for Mycobank ]
- [x] Set Full name bug with varieties
- [] Initial taxonomy on install (migrated to #57)
- [x] Remove Log from calls
- [x] Add specialist seeds
- [x] Validate author OR author id
- [x] Validate all ranks > gen. MUST have a parent
- [] Taxon dup: 1. Provide a better message for error inserting duplicate taxon. 2. Change key to [ name, parent, author ]. 3. Enforce that only one identical name can be valid. (migrated to #61)
- [] Support morphospecies (migrated to #55)
- [x] PHP7: remove "public const"
- [x] Bug: check for null before array_key_exists??
- [x] Add error messages to translation file
- [x] Get Mobot working with dot, encode to %2E
- [x] Add links to Tropicos / IPNI / Mycobank when search failed
- [] Autocomplete for filling "parent" and "senior" when registering taxa (migrated to #59)
